---
- name: Add pimaster DNS entry
  lineinfile: 
    dest: "/etc/dnsmasq_static_hosts.conf"
    line: "{{ item }}"
    state: present
  loop: "{{ dns_entries }}"
  become: yes
  tags: [ 'dns_entries']
