---
- name: Create ESXi TFTP boot dir
  file:
    path: "{{ item.tftp_root }}esxi{{ item.major_version }}{{ item.minor_version }}"
    state: directory
  with_items: "{{ esxi_host }}"
  tags: [ 'esxi_build']

- name: Copy files from local to PXE/TFTP host
  copy:
    src: "{{ role_path }}/files/esxi/"
    dest: "{{ item.tftp_root }}esxi{{ item.major_version }}{{ item.minor_version }}"
    force: no
  with_items: "{{ esxi_host }}"
  when: refresh | default(False)
  tags: [ 'esxi_build']

- name: Using sed to remove "/" from boot.cfg
  shell:  sed -i 's/\///g' {{ item.tftp_root }}esxi{{ item.major_version }}{{ item.minor_version }}/boot.cfg
  with_items: "{{ esxi_host }}"
  tags: [ 'esxi_build']

- name: Creates directory
  file:
    path: "{{ item.nginx_root }}/ks"
    state: directory
  with_items: "{{ esxi_host }}"
  tags: [ 'esxi_build']

- name: Get SSH Key 
  shell: cat {{ ansible_env.HOME }}/.ssh/id_rsa.pub | awk '{split($0,a," "); print a[2]}'
  register: ssh_key_var
  tags: ['ssh_key_ks','esxi_build']

- name: Set SSH pub key variable
  set_fact:
    ssh_pub_key: "{{ ssh_key_var }}"
  tags: ['ssh_key_ks','esxi_build']

- name: Create ks file for automated install
  template:
    src: ks.cfg.j2
    dest: "{{ item.nginx_root }}/ks/ks.cfg"
  with_items: "{{ esxi_host }}"
  tags: [ 'esxi_build']

- name: replace line
  lineinfile: 
    dest: "{{ item.tftp_root }}esxi{{ item.major_version }}{{ item.minor_version }}/boot.cfg"
    #dest: /opt/tftpboot/esxi67u3/boot.cfg
    regexp: '^(.*)kernelopt(.*)$' 
    line: "kernelopt=ks=http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}/ks/ks.cfg"
  with_items: "{{ esxi_host }}"
  tags: [ 'esxi_build']
#- name: Write PXE config
