---
- name: Wake on Lan physical host
  shell:  wakeonlan {{ item.macaddress }}
  with_items: "{{ esxi_host }}"
  when: production | default(False)

- name: Power on virtualbox VM
  local_action: VBoxManage startvm "TestPxE"
  when: testing | default(False)