---
- name: Wake on Lan physical host
  shell:  wakeonlan {{ item.macaddress }}
  with_items: "{{ esxi_host }}"
  when: production | default(False)
  tags: [ 'esxi_install']

- name: Power on virtualbox VM
  shell: VBoxManage startvm "TestPxE"
  delegate_to: localhost
  when: testing | default(False)
  tags: [ 'esxi_install']

- command: /bin/ping -c 1 {{ item.ip_addr }}
  register: result
  retries: 150
  delay: 20
  until: result is not failed
  with_items: "{{ esxi_host }}"
  tags: [ 'esxi_install']

- name: Replace "MENU DEFAULT"
  lineinfile: 
    dest: "/opt/tftpboot/pxelinux.cfg/default"
    regexp: '^(.*)MENU DEFAULT(.*)$' 
    state: absent
  with_items: "{{ esxi_host }}"
  tags: [ 'esxi_install_post']

- name: Add "MENU DEFAULT"
  lineinfile:
    dest: "/opt/tftpboot/pxelinux.cfg/default"
    line: "  MENU DEFAULT"
    insertafter: '^(.*)LOCALBOOT 0x80(.*)$'
  with_items: "{{ esxi_host }}"
  tags: [ 'esxi_install_post']