---
- name: Create ESXi TFTP boot dir
  file:
    path: "{{ item.tftp_root }}esxi{{ item.major_version }}{{ item.minor_version }}"
    state: directory
  with_items: "{{ esxi_host }}"

- name: Copy files from local to PXE/TFTP host
  copy:
    src: "{{ role_path }}/files/esxi/"
    dest: "{{ item.tftp_root }}esxi{{ item.major_version }}{{ item.minor_version }}"
    force: no
  with_items: "{{ esxi_host }}"

- name: Using sed to remove "/" from boot.cfg
  shell:  sed -i 's/\///g' {{ item.tftp_root }}esxi{{ item.major_version }}{{ item.minor_version }}/boot.cfg
  with_items: "{{ esxi_host }}"

- name: Creates directory
  file:
    path: /opt/www/html/ks
    state: directory

- name: Create ks file for automated install
  template:
    src: ks.cfg.j2
    dest: /opt/www/html/ks/ks.cfg
  with_items: "{{ esxi_host }}"

- name: replace line
  lineinfile: 
    dest: "{{ item.tftp_root }}esxi{{ item.major_version }}{{ item.minor_version }}/boot.cfg"
    regexp: '^(.*)kernelopt(.*)$' 
    line: 'kernelopt=ks=http://192.168.1.253/ks/ks.cfg'
    backrefs: yes
  with_items: "{{ esxi_host }}"
#- name: Write PXE config
