---
- name: Restart pimaster
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  become: yes
  tags: [ 'esxi_install' ]

- name: wait for 10 seconds
  pause:
    seconds: 10
  tags: [ 'esxi_install' ]

- name: wait for the system to reboot
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 60
  tags: [ 'esxi_install' ]

- name: Wake on Lan physical host
  shell:  wakeonlan {{ item.macaddress }}
  with_items: "{{ esxi_host }}"
  when: production | default(False)
  tags: [ 'esxi_install']

- name: Power on virtualbox VM
  shell: VBoxManage startvm "TestPxE"
  delegate_to: localhost
  when: testing | default(False)
  tags: [ 'esxi_install']

- command: /bin/ping -c 1 {{ item.ip_addr }}
  register: result
  retries: 300
  delay: 10
  until: result is not failed
  with_items: "{{ esxi_host }}"
  tags: [ 'esxi_install']

- name: Replace "MENU DEFAULT"
  lineinfile: 
    dest: "{{ item.tftp_root }}pxelinux.cfg/default"
    regexp: '^(.*)MENU DEFAULT(.*)$' 
    state: absent
  with_items: "{{ esxi_host }}"
  tags: [ 'esxi_install_post']

- name: Add "MENU DEFAULT"
  lineinfile:
    dest: "{{ item.tftp_root }}pxelinux.cfg/default"
    line: "  MENU DEFAULT"
    insertafter: '^(.*)LOCALBOOT 0x80(.*)$'
  with_items: "{{ esxi_host }}"
  tags: [ 'esxi_install_post']