---
- name: Create ESXi TFTP boot dir
  file:
    path: "{{ item.tftp_root }}"ESXi{{ item.major_version }}{{ minor_version }}
    state: directory
  with_items: "{{ esxi-host }}"

- name: Copy files from local to PXE/TFTP host
    copy:
      src: "{{ role_path }}"/files/esxi/*
      dest: "{{ item.tftp_root }}"ESXi{{ item.major_version }}{{ minor_version }}
      force: no
  with_items: "{{ esxi-host }}"
- name: Using sed to remove "/" from boot.cfg
  shell:  sed -i 's/\///g' {{ item.tftp_root }}ESXi{{ item.major_version }}{{ minor_version }}/boot.cfg
- name: Append config to boot.cfg
- name: Write PXE config