---
- name: Install git
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git
  tags: ["git", "extra_packages"]

- name: Install ansible
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - ansible
  tags: ["ansible", "extra_packages"]
