---
- name: Install git
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git
  tags: ["git", "extra_packages"]

- name: Instaall ansible
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - ansible
  tags: ["ansible", "extra_packages"]

- name: Instaall dnsutils
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - dnsutils
  tags: ["dnsutils", "extra_packages"]

- name: Copy ovftool
  copy:
    src: "{{ role_path }}/files/ovftool/"
    dest: "/mnt/usb/ovftool"
    force: no
  tags: ["ovftool", "extra_packages"]

- name: get files
  find:
    paths: /mnt/usb/ovftool
    file_type: "file"
  register: find_result

- name: Execute mod file
  shell: chmod +x <file_name> {{ item.path | basename }}
  run_once: true
  with_items: "{{ find_result.files }}"
  tags: ["ovftool", "extra_packages"]
