---
- name: Install git
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git
  tags: ["git", "extra_packages"]

- name: Instaall ansible
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - ansible
  tags: ["ansible", "extra_packages"]

- name: Instaall dnsutils
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - dnsutils
  tags: ["dnsutils", "extra_packages"]

#- name: Copy ovftool
#  copy:
#    src: "{{ role_path }}/files/ovftool/"
#    dest: "/mnt/usb/ovftool"
#    force: no
#  tags: ["ovftool", "extra_packages"]

#- name: find the file we just copied without knowing the name
#  find:
#    paths: /mnt/usb/ovftool/
#    file_type: "file"
#    patterns: "*"
#  register: find_result
#  tags: ["ovftool", "extra_packages"]
#- debug:
#    var: find_result

#- name: Add execute permission to file
#  file:
#    path: "{{ item.path }}"
#    state: file
#    mode: "u+x,g+x,o+x"  
#  with_items: "{{ find_result.files }}"
#  tags: ["ovftool", "extra_packages"]

- name: Copy ovftool
  copy:
    src: "/usr/lib/vmware-ovftool"
    dest: "/mnt/usb/ovftool"
    force: no
  tags: ["ovftool", "extra_packages"]