---

- name: Create project directory
  file:
    path: "{{ ansible_env.HOME }}/pimaster-esxiconfig"
    state: directory
    owner: homelab
    group: users
  tags: [ 'git_repos']

- name: Git clone repo
  git:
    repo: git@github.com:serokles/pimaster-esxiconfig.git
    dest: "{{ ansible_env.HOME }}/pimaster-esxiconfig/"
    accept_hostkey: yes
  become: no
  tags: [ 'git_repos']  