---
- name: Install Dnsmasq
  package:
    name: dnsmasq
    state: present
  tags: [ 'dnsmasq' ]

- name: Install syslinux-common
  package:
    name: syslinux-common
    state: present
  tags: [ 'dnsmasq' ]

- name: Creates directory
  file:
    path: /opt/tftpboot
    state: directory
  tags: [ 'dnsmasq' ]

- name: Set configuration file
  template:
    src: etc_dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    validate: 'dnsmasq --test --conf-file=%s'
  with_items: "{{ dnsmasq_vars }}"
  notify: restart_dnsmasq
  tags: [ 'dnsmasq' ]

- name: Creates static hosts file
  file:
    path: "{{ item.dns_statichosts }}"
    state: touch
  with_items: "{{ dnsmasq_vars }}"
  notify: restart_dnsmasq
  tags: [ 'dnsmasq' ]

- name: Create logrotate file for DHCP logs
  template:
    src: dnsmasq_logrotate.j2
    dest: /etc/logrotate.d/dnsmasq
  notify: restart_dnsmasq
  tags: [ 'dnsmasq' ]

- name: Make sure Dnsmasq is running
  service:
    name: dnsmasq
    state: started
    enabled: yes
  tags: [ 'dnsmasq' ]

- name: create users
  user: name=nginx
        uid=1010
        state=present
        shell=/bin/bash
  tags: [ 'nginx']

- name: Install nginx
  package:
    name: nginx
    state: present
  tags: [ 'nginx' ]

- name: Creates directory
  file:
    path: /opt/www/html
    state: directory
  tags: [ 'nginx']

- name: copy nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: nginx
    group: nginx
    mode: u=rw,g=r,o=r
  with_items: "{{ nginx_vars }}"
  notify: restart_nginx
  tags: [ 'nginx']

- name: download syslinux
  get_url: 
    url: https://www.kernel.org/pub/linux/utils/boot/syslinux/3.xx/syslinux-3.86.tar.gz
    dest: /home/homelab/syslinux-3.86.tar.gz
    checksum: sha256:c5fb189978d1a2d2041cc69a2956981e305ecd5cb9ce03f589d3fd1f1c434038
  tags: [ 'pxe']

- name: Unarchive syslinux
  unarchive:
    src: /home/homelab/syslinux-3.86.tar.gz
    dest: /home/homelab/
    remote_src: yes
  tags: [ 'pxe']

- name: Ansible copy files remote to remote
  copy:
    src: /home/homelab/syslinux-3.86/core/pxelinux.0
    dest: /opt/tftpboot/
    remote_src: yes
  tags: [ 'pxe']

- name: Ansible copy files remote to remote
  copy:
    src: /home/homelab/syslinux-3.86/com32/menu/vesamenu.c32
    dest: /opt/tftpboot/
    remote_src: yes
  tags: [ 'pxe']

- name: Create pxelinux.cfg directory
  file:
    path: /opt/tftpboot/pxelinux.cfg
    state: directory
  tags: [ 'pxe']

- name: Create default config for pxelinux.cfg
  template:
    src: default.j2
    dest: /opt/tftpboot/pxelinux.cfg/default
  with_items: "{{ esxi_host }}"
  tags: [ 'pxe']

- name: Install Wake-On-Lan
  package:
    name: wakeonlan
    state: present
  tags: [ 'wol' ]