---
### Users that must be present on the system
dnsmasq_vars:
  - port: 0
    log: true
    network_range: 192.168.1.0
    dhcp_proxy: true
    tftp: true
    tftp_root: /opt/tftpboot
    pxe_service: 'X86PC,"PXE Boot...",pxelinux'

nginx_vars:
  - nginx_service_name: nginx
    nginx_port: 80
    nginx_root: /opt/www/html

esxi_host:
  - hostname: "esx1.houseofbears.co.uk"
    macaddress: 34:17:eb:ba:2c:c1
    major_version: "67"
    minor_version: "u3"
    tftp_root: /opt/tftpboot/
    refresh: true
