---
### Users that must be present on the system
dnsmasq_vars:
  - port: 0
    log: true
    network_range: 192.168.1.0
    dhcp_proxy: true
    tftp: true
    tftp_root: /opt/tftpboot
    pxe_service: 'X86PC,"PXE Boot...",pxelinux'